graphql:
  packages:
    - "com.moneyforward.ktnowhow"
spring:
  datasource:
    url: jdbc:h2:mem:ktnowhow
    # url: jdbc:h2:~/.h2/ktnowhow
    driverClassName: org.h2.Driver
    username: sa
    password:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: false